import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingTop: 48,
    backgroundColor: "#1c4722",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 4,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  menuButton: {
    padding: 8,
    borderRadius: 8,
  },
  topBarTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.3,
  },
  container: {
    padding: 20,
    backgroundColor: "#E6DED1",
    flexGrow: 1,
  },
  imageContainer: {
    marginBottom: 24,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    position: "relative", // Added relative positioning for retake button
  },
  image: {
    width: "100%",
    height: 300,
    resizeMode: "cover",
  },
  retakeButton: {
    position: "absolute", // Added retake button styles
    bottom: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#1c4722",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  retakeButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#5f6368",
    fontWeight: "500",
  },
  messageCard: {
    backgroundColor: "#ffffff",
    padding: 32,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  errorText: {
    fontSize: 16,
    color: "#c62828",
    textAlign: "center",
    marginTop: 16,
    fontWeight: "600",
    lineHeight: 24,
  },
  warningText: {
    fontSize: 16,
    color: "#f57c00",
    textAlign: "center",
    marginTop: 16,
    fontWeight: "500",
    lineHeight: 24,
  },
  healthyCard: {
    backgroundColor: "#ffffff",
    padding: 40,
    borderRadius: 16,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#1c4722",
    shadowColor: "#1c4722",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  healthyTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1c4722",
    marginTop: 16,
    letterSpacing: 0.3,
  },
  healthySubtitle: {
    fontSize: 16,
    color: "#5f6368",
    marginTop: 8,
    fontWeight: "500",
  },
  resultsContainer: {
    gap: 16,
  },
  resultsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  resultsTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#202124",
    letterSpacing: 0.3,
  },
  diseaseCard: {
    backgroundColor: "#ffffff",
    padding: 20,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#c62828",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 16,
  },
  diseaseHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    gap: 12,
  },
  diseaseIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#ffebee",
    alignItems: "center",
    justifyContent: "center",
  },
  diseaseName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#c62828",
    flex: 1,
    letterSpacing: 0.2,
  },
  diseaseSection: {
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1c4722",
    letterSpacing: 0.3,
  },
  sectionBody: {
    fontSize: 15,
    color: "#3c4043",
    lineHeight: 22,
    paddingLeft: 26,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  overlayTouchable: {
    flex: 1,
  },
  sidePanel: {
    width: "80%",
    backgroundColor: "#ffffff",
    paddingTop: 48,
    paddingHorizontal: 20,
    paddingBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  sidePanelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e8eaed",
  },
  historyTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1c4722",
    letterSpacing: 0.3,
  },
  historySubtitle: {
    fontSize: 14,
    color: "#5f6368",
    marginTop: 4,
  },
  closeButton: {
    padding: 4,
  },
  historyCard: {
    marginBottom: 12,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#f8faf9",
    borderWidth: 1,
    borderColor: "#e8eaed",
  },
  historyCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  historyDate: {
    fontSize: 13,
    color: "#5f6368",
    fontWeight: "500",
  },
  historyStatusContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  healthyBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#e8f5e9",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  historyHealthy: {
    fontSize: 14,
    color: "#1c4722",
    fontWeight: "600",
  },
  diseasedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#ffebee",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    flex: 1,
  },
  historyDiseased: {
    fontSize: 14,
    color: "#c62828",
    fontWeight: "600",
    flex: 1,
  },
  warningBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#fff3e0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  historyWarning: {
    fontSize: 14,
    color: "#f57c00",
    fontWeight: "600",
  },
  emptyHistory: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyHistoryText: {
    fontSize: 16,
    color: "#9aa0a6",
    marginTop: 12,
    fontWeight: "500",
  },
})
