import { StyleSheet } from "react-native";
const COLORS = {
  primaryGreen: "#1D492C",
  accentGreen: "#84cc16",
  pastelGreen: "#BDE08A",
  lightGreen: "#f0fdf4",
  darkGreen: "#143820",
  mutedGreen: "#4C6444",
  error: "#8a1c14ff",
  grayText: "#666",
  border: "#e0e0e0",
  white: "#ffffff",
  bgCOlor: "#cfc4b2ff",
  primaryBrown: "#8A6440",
  darkBrown: "#4D2D18",
};

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 60,
  },
  logo: {
    height: 50,
    resizeMode: "contain",
    marginBottom: 30,
  },
  title: {
    fontSize: 40,
    fontWeight: "900",
    color: "white",
    textAlign: "center",
    textShadowColor: COLORS.pastelGreen,
    textShadowOffset: { width: 0, height: 2 }, 
    textShadowRadius: 20,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 5,
    alignSelf: "center"
  },
  logo2: {
    height: 50,
    width: 50,
    resizeMode: "contain",
    marginRight: 2,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.5,
    elevation: 5,
  },
  subtitle: {
    color: "#cce0cc",
    textAlign: "center",
    marginBottom:70,
    fontSize: 15
  },
  infoWrapper: {
    width: "90%",
    marginBottom: 50,
  },
  infoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.lightGreen,
    borderRadius: 30,
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginVertical: 8,
    minWidth: "55%",
    maxWidth: "75%",
    alignSelf: "flex-start",
    elevation: 20,
    shadowColor: COLORS.accentGreen,
    shadowOffset: { width: 10, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  infoText: {
    fontSize: 18,
    color: COLORS.primaryGreen,
    flexShrink: 1,
  },
  leftCard: {
    alignSelf: "flex-start",
    marginLeft: 20,
    marginBottom: 60,
  },
  rightCard: {
    alignSelf: "flex-end",
    marginRight: 20,
    marginBottom: 60,
  },
  tiltLeft: {
    transform: [{ rotate: "-5deg" }],
  },
  tiltRight: {
    transform: [{ rotate: "5deg" }],
  },
  icon: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
  bold: {
    fontWeight: "700",
  },
  getStartedButton: {
    position: "absolute",
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: COLORS.pastelGreen,
    paddingVertical: 20,
    borderRadius: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  getStartedText: {
    color: COLORS.white,
    fontWeight: "900",
    fontSize: 18,
    textShadowColor: "rgba(0, 0, 0, 0.28)", 
    textShadowOffset: { width: 2, height: 3 }, 
    textShadowRadius: 5,
    textAlign: "center",
  },
});
