import { StyleSheet } from "react-native"


export const COLORS = {
  primaryGreen: "#1D492C",
  accentGreen: "#84cc16",
  pastelGreen: "#BDE08A",
  lightGreen: "#f0fdf4",
  darkGreen: "#143820",
  mutedGreen: "#4C6444",
  grayText: "#666",
  border: "#e0e0e0",
  white: "#ffffff",
  bgCOlor: "#cfc4b2ff",
  primaryBrown: "#8A6440",
  secondaryBrown: "#ecc096ff",
  darkBrown: "#4D2D18",
  accent: "#FF6F00",
  accentLight: "#FFA726",
  background: "#CBBA9E",
  cardBackground: "#FFFFFF",
  textPrimary: "#1A1A1A",
  textSecondary: "#6B7280",
  textLight: "#9CA3AF",

  // Status colors
  success: "#4CAF50",
  warning: "#FFC107",
  error: "#8a1c14ff",
  info: "#2196F3",
}
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#CBBA9E",
  },

  headerBackground: {
    paddingTop: 50,
    paddingBottom: 40,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  greeting: {
    fontSize: 20,
    fontWeight: "700",
    color: "white",
    letterSpacing: 0.3,
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },

  plantCard: {
    backgroundColor: "#1c4722",
    borderRadius: 5,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 30,
    marginBottom: 24,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    overflow: "hidden",
  },
  plantCardContent: {
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
  },
  plantImageWrapper: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginRight: 16,
    overflow: 'hidden',
  },
  plantImage: {
    width: '100%',
    height: '100%',
  },
  plantImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  plantImagePlaceholderText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 10,
    fontWeight: '500',
    marginTop: 4,
  },
  plantTextWrapper: {
    flex: 1,
  },
  plantName: {
    fontSize: 24,
    fontWeight: "800",
    color: COLORS.lightGreen,
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  plantTitle: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    marginTop: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  plantDetails: {
    color: "white",
    fontSize: 14,
    marginTop: 4,
    fontWeight: "500",
  },
  findPlantsButton: {
    marginTop: 20,
    backgroundColor: COLORS.lightGreen,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  findPlantsText: {
    color: "#1c4722",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.5,
  },

  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  sectionTitle: {
    marginBottom: 16,
    fontSize: 20,
    fontWeight: "900",
    color: COLORS.darkBrown,
    marginLeft: 4,
    letterSpacing: 0.3,
  },

  // Condition Card Styles - Redesigned
  conditionCard: {
    backgroundColor: "#8a644056",
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  conditionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
  },
  conditionHeaderLeft: {
    flex: 1,
  },
  conditionStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F8F0",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    alignSelf: "flex-start",
  },
  conditionStatusText: {
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  conditionSubtitle: {
    fontSize: 12,
    color: COLORS.primaryBrown,
    marginTop: 8,
    fontWeight: "500",
  },

  // Metrics Grid
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  metricCard: {
    width: "48%",
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  metricHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  metricLabel: {
    fontSize: 11,
    color: COLORS.primaryBrown,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  metricValue: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  metricRange: {
    fontSize: 11,
    color: COLORS.darkBrown,
    fontStyle: "italic",
  },
  metricStatus: {
    fontSize: 10,
    fontWeight: "600",
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Soil Moisture Card - Completely Redesigned
  soilMoistureCard: {
    backgroundColor: "#8a644056",
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  soilMoistureHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    paddingBottom: 16,
  },
  soilMoistureTitle: {
    color: COLORS.primaryBrown,
    fontWeight: "800",
    fontSize: 14,
    letterSpacing: 0.3,
  },
  soilViewButton: {
    backgroundColor: "#4d7f39",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    elevation: 2,
  },
  soilViewText: {
    color: "white",
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  moistureMainDisplay: {
    backgroundColor: "#F8FFF4",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureValueContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 8,
  },
  moistureLargeValue: {
    fontSize: 64,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: -2,
  },
  moistureUnit: {
    fontSize: 32,
    fontWeight: "700",
    color: "#4d7f39",
    marginLeft: 4,
  },
  moistureLabel: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  moistureRangeContainer: {
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureRangeLabel: {
    fontSize: 11,
    color: "#999",
    textAlign: "center",
    marginBottom: 4,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  moistureRangeValue: {
    fontSize: 16,
    color: "#2D5016",
    fontWeight: "700",
    textAlign: "center",
  },
  moistureStatusRow: {
    marginBottom: 16,
  },
  moistureStatusCard: {
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureStatusHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  moistureStatusText: {
    fontSize: 18,
    fontWeight: "800",
    marginLeft: 12,
    letterSpacing: 0.3,
  },
  moistureMessage: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
    marginLeft: 36,
  },
  moistureBarContainer: {
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureBarLabel: {
    fontSize: 12,
    color: "#666",
    fontWeight: "600",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  moistureBarTrack: {
    height: 12,
    backgroundColor: "#E8E8E8",
    borderRadius: 6,
    overflow: "hidden",
    marginBottom: 8,
  },
  moistureBarFill: {
    height: "100%",
    borderRadius: 6,
  },
  moistureBarMarkers: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  moistureBarMarker: {
    fontSize: 10,
    color: "#999",
    fontWeight: "600",
  },
  plantHealthIndicator: {
    flexDirection: "row",
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  plantHealthIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    elevation: 2,
  },
  plantHealthText: {
    flex: 1,
  },
  plantHealthTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2D5016",
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  plantHealthDescription: {
    fontSize: 12,
    color: "#666",
    lineHeight: 18,
    fontWeight: "500",
  },

  // History Card - Redesigned
  historyCard: {
    backgroundColor: "#8a644056",
    borderRadius: 24,
    padding: 20,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  historyHeader: {
    marginBottom: 16,
  },
  historyHeaderRow: {
    flexDirection: "column",
    gap: 12,
  },
  historyTitle: {
    color: COLORS.primaryBrown,
    fontWeight: "800",
    fontSize: 18,
    letterSpacing: 0.3,
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.lightGreen,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  legendColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  legendText: {
    color: "#666",
    fontSize: 11,
    fontWeight: "600",
  },
  historyScrollView: {
    marginTop: 8,
  },
  historyScrollContent: {
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  scrollableHistoryDayWrapper: {
    marginRight: 12,
    alignItems: "center",
  },
  cleanDayBox: {
    width: 80,
    height: 100,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  cleanDayText: {
    color: "white",
    fontWeight: "700",
    fontSize: 11,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  cleanDateText: {
    color: "white",
    fontWeight: "800",
    fontSize: 32,
    marginBottom: 4,
    letterSpacing: -1,
  },
  cleanStatusText: {
    color: "white",
    fontWeight: "700",
    fontSize: 10,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Footer
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#1c4722",
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },

  // Modal Styles
  plantModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    padding: 20,
  },
  plantModalContainer: {
    backgroundColor: COLORS.lightGreen,
    borderRadius: 24,
    padding: 24,
    maxHeight: "85%",
    elevation: 12,
  },
  plantModalTitle: {
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 16,
    color: COLORS.primaryGreen,
    letterSpacing: 0.3,
  },
  selectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 10,
    color: COLORS.primaryGreen,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  chipScrollContainer: {
    maxHeight: 48,
    marginBottom: 12,
  },
  selectionChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#F0F8F0",
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  selectionChipActive: {
    backgroundColor: "#4d7f39",
    borderColor: "#4d7f39",
  },
  selectionChipText: {
    fontSize: 13,
    color: "#2D5016",
    fontWeight: "600",
  },
  selectionChipTextActive: {
    color: "#fff",
    fontWeight: "700",
  },
  categoryChipContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  plantList: {
    borderTopWidth: 1,
    borderColor: "#E8E8E8",
    marginTop: 8,
    maxHeight: 200,
  },
  plantItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderColor: "#F5F5F5",
    backgroundColor: "white",
  },
  plantItemContent: {
    flex: 1,
    marginRight: 12,
  },
  plantItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  plantItemName: {
    fontSize: 16,
    color: "#2D5016",
    fontWeight: "700",
    flex: 1,
    letterSpacing: 0.3,
  },
  recommendedBadge: {
    backgroundColor: "#4d7f39",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  recommendedText: {
    fontSize: 10,
    color: "#fff",
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  plantItemLocation: {
    fontSize: 13,
    color: "#666",
    fontStyle: "italic",
  },
  noLocationsText: {
    textAlign: "center",
    color: "#999",
    fontStyle: "italic",
    paddingVertical: 32,
    fontSize: 14,
  },
  closeModalBtn: {
    marginTop: 16,
    backgroundColor: COLORS.mutedGreen,
    paddingVertical: 14,
    borderRadius: 20,
    alignItems: "center",
    elevation: 2,
  },
  closeModalText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.5,
  },

  // History Modal Styles
  historyModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  historyModalContainer: {
    width: "95%",
    maxHeight: "90%",
    backgroundColor: "white",
    borderRadius: 24,
    padding: 24,
    elevation: 12,
  },
  historyModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#E8F5E8",
  },
  historyModalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: 0.3,
  },
  historyModalDate: {
    fontSize: 14,
    color: "#666",
    marginTop: 6,
    fontWeight: "500",
  },
  historyCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
  },
  historySummaryCard: {
    backgroundColor: "#F8FFF4",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  historyPlantInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  historyPlantName: {
    fontSize: 20,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: 0.3,
  },
  historyStatusBadge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    elevation: 2,
  },
  historyStatusText: {
    color: "white",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  historyStatsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E8F5E8",
  },
  historyStat: {
    alignItems: "center",
  },
  historyStatLabel: {
    fontSize: 11,
    color: "#666",
    marginBottom: 6,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  historyStatValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: -0.5,
  },
  historyAveragesCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  historySectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#2D5016",
    marginBottom: 16,
    letterSpacing: 0.3,
  },
  historyMetricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  historyMetricItem: {
    width: "48%",
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  historyMetricLabel: {
    fontSize: 11,
    color: "#666",
    marginBottom: 6,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  historyMetricValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: -0.5,
  },
  historyTimelineCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  timelineScroll: {
    marginTop: 12,
  },
  timelineItem: {
    width: 140,
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  timelineTimestamp: {
    fontSize: 13,
    fontWeight: "700",
    color: "#2D5016",
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  timelineReadings: {
    alignItems: "flex-start",
    width: "100%",
  },
  timelineReadingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  timelineReading: {
    fontSize: 12,
    color: "#666",
    marginLeft: 6,
    fontWeight: "500",
  },
  historyGraphCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  simpleGraph: {
    flexDirection: "row",
    alignItems: "flex-end",
    height: 140,
    marginTop: 16,
    paddingHorizontal: 8,
  },
  graphColumn: {
    flex: 1,
    alignItems: "center",
    height: "100%",
    justifyContent: "flex-end",
  },
  graphBar: {
    width: 16,
    marginBottom: 10,
    borderRadius: 8,
    minHeight: 12,
    elevation: 2,
  },
  graphLabel: {
    fontSize: 11,
    color: "#666",
    fontWeight: "600",
  },

  // Live Plant Suggestions Styles
  liveSuggestionsCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    marginVertical: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  liveSuggestionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  liveSuggestionsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.primaryGreen,
  },
  liveSuggestionsSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 15,
  },
  expandButton: {
    padding: 8,
  },
  suggestionsContent: {
    marginTop: 10,
  },
  suggestionSection: {
    marginBottom: 20,
  },
  suggestionSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  suggestionSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  suggestionScroll: {
    flexDirection: 'row',
  },
  suggestionPlantCard: {
    backgroundColor: COLORS.lightGreen,
    borderRadius: 12,
    padding: 12,
    marginRight: 12,
    minWidth: 140,
    maxWidth: 160,
  },
  compatibleCard: {
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  incompatibleCard: {
    borderWidth: 2,
    borderColor: '#FF9800',
  },
  suggestionPlantName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primaryGreen,
    marginBottom: 8,
    textAlign: 'center',
  },
  compatibilityScore: {
    alignItems: 'center',
    marginBottom: 8,
  },
  scoreText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  scoreStars: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  suggestionLocation: {
    fontSize: 11,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },

  // New Live Suggestions Styles (for compatibility analysis)
  liveSuggestionsMainContainer: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  liveCompatibilityCard: {
    width: 120,
    padding: 12,
    marginRight: 12,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
  },
  compatiblePlantCard: {
    backgroundColor: '#e8f5e8',
    borderColor: '#4CAF50',
  },
  incompatiblePlantCard: {
    backgroundColor: '#fff8e1',
    borderColor: '#FF8C00',
  },
  liveCompatibilityRating: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  liveCompatibilityScore: {
    fontSize: 10,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  collapsedCompatibilityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    marginBottom: 8,
  },
  collapsedCompatibilityText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.primaryGreen,
  },

  // ===== ENHANCED CATEGORY & FILTER STYLES =====
  categoryTabsContainer: {
    marginTop: 16,
    marginBottom: 12,
  },
  categoryTabsScroll: {
    paddingHorizontal: 4,
  },
  categoryTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 10,
    backgroundColor: '#f8f9fa',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#e9ecef',
  },
  categoryTabActive: {
    backgroundColor: COLORS.primaryGreen,
    borderColor: COLORS.primaryGreen,
  },
  categoryTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.primaryGreen,
    marginLeft: 6,
  },
  categoryTabTextActive: {
    color: 'white',
    fontWeight: '700',
  },

  // Status Filter Styles
  statusFilterContainer: {
    flexDirection: 'row',
    paddingHorizontal: 4,
    marginBottom: 16,
  },
  statusFilterTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1.5,
  },
  statusFilterTabActive: {
    backgroundColor: COLORS.primaryGreen,
  },
  statusFilterText: {
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  statusFilterTextActive: {
    color: 'white',
    fontWeight: '700',
  },

  // Plant Suggestions Grid
  plantSuggestionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  plantSuggestionCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  plantCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  plantCompatibilityStars: {
    flexDirection: 'row',
  },
  plantSuggestionName: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.primaryGreen,
    marginBottom: 4,
  },
  plantSuggestionScore: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginBottom: 6,
  },
  plantLocationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  plantLocationText: {
    fontSize: 10,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },

  // No Results Styles
  noResultsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  noResultsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginTop: 12,
    marginBottom: 4,
  },
  noResultsText: {
    fontSize: 13,
    color: COLORS.textLight,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 20,
  },

  // ===== ANALYSIS PAGE MATCHING STYLES =====
  scrollView: {
    flex: 1,
  },
  location: {
    fontSize: 14,
    color: '#E0E0E0',
    marginTop: 4,
  },
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusConnected: {
    backgroundColor: COLORS.success,
  },
  statusDisconnected: {
    backgroundColor: COLORS.error,
  },
  statusChecking: {
    backgroundColor: COLORS.warning,
  },
  statusText: {
    fontSize: 12,
    color: 'white',
    marginLeft: 4,
    fontWeight: '600',
  },
  sensorContainer: {
    backgroundColor: '#fff',
    margin: 16,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sensorHeader: {
    marginBottom: 16,
  },
  sensorTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.primaryGreen,
    marginBottom: 4,
  },
  lastUpdate: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  sensorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  sensorCard: {
    width: '48%',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  sensorLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginTop: 4,
    textAlign: 'center',
  },
  sensorValue: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.primaryGreen,
    marginTop: 2,
    textAlign: 'center',
  },

  // Category Container (matching analysis page)
  categoryContainer: {
    marginBottom: 20,
  },
  categoryScrollView: {
    marginTop: 10,
  },
  categoryCard: {
    width: 120,
    backgroundColor: "#f0fdf481",
    borderRadius: 16,
    padding: 16,
    marginRight: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    borderWidth: 2,
    borderColor: "#E2E8F0",
  },
  activeCategoryCard: {
    borderColor: COLORS.lightGreen,
    backgroundColor: "#F0F9F4",
    elevation: 4,
    shadowOpacity: 0.12,
  },
  categoryIconContainer: {
    marginBottom: 10,
  },
  categoryName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
    textAlign: "center",
    marginTop: 6,
  },
  activeCategoryName: {
    color: "#1c4722",
  },
  categoryCount: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 3,
    fontWeight: "500",
  },

  // Status Summary (matching analysis page)
  categorySummary: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    padding: 16,
  },
  categorySummaryTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: 'white',
    marginBottom: 4,
    textAlign: 'center',
  },
  categorySummarySubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    marginBottom: 16,
  },
  statusSummaryScroll: {
    marginTop: 8,
  },
  statusSummaryScrollContent: {
    paddingHorizontal: 4,
  },
  statusSummaryItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    padding: 12,
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  activeStatusItemCard: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(255,255,255,0.8)',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  statusTextContainer: {
    flex: 1,
  },
  statusSummaryText: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
  },
  activeStatusText: {
    color: '#1c4722',
    fontWeight: '700',
  },
  statusCount: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 2,
  },
  checkmark: {
    marginLeft: 8,
  },

  // Detailed View (matching analysis page)
  detailView: {
    marginTop: 10,
    marginHorizontal: 16,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F9F4",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 15,
    alignSelf: "flex-start",
    borderWidth: 1.5,
    borderColor: "#D1E7DD",
  },
  backButtonText: {
    fontSize: 14,
    color: "#1c4722",
    fontWeight: "700",
    marginLeft: 6,
  },
  detailedRecommendationCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 18,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  plantInfo: {
    flex: 1,
  },
  plantDetailName: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.primaryGreen,
    marginBottom: 4,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  locationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  locationText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  compatibilitySection: {
    marginBottom: 16,
  },
  compatibilityTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.primaryGreen,
    marginBottom: 8,
  },
  compatibilityScoreContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scoreDetailText: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  scoreStarsContainer: {
    flexDirection: 'row',
  },
  parameterComparison: {
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingTop: 16,
  },
  sectionSubtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.primaryGreen,
    marginBottom: 12,
  },
  parameterRow: {
    marginBottom: 12,
  },
  parameterLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  parameterValue: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 18,
  },

  // List View (matching analysis page)
  recommendationsList: {
    marginHorizontal: 16,
  },
  listHeader: {
    marginBottom: 16,
  },
  listTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.primaryGreen,
    marginBottom: 4,
  },
  listSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  recommendationCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  compatibilityInfo: {
    alignItems: 'flex-end',
  },
  statusIndicatorBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 8,
  },
  statusIndicatorText: {
    fontSize: 12,
    color: 'white',
    fontWeight: '600',
    marginLeft: 4,
  },

  // Loading
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.textSecondary,
  },

  // Chart Container
  chartContainer: {
    backgroundColor: "#f0fdf476",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
    color: COLORS.primaryBrown,
    letterSpacing: 0.3,
  },
  chartSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 16,
  },


  // LIVE PLANT MATCHING STYLES
  liveMatchesCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: COLORS.accentGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 2,
    borderColor: COLORS.accentGreen,
    // Enhanced visual prominence for top position
    borderTopWidth: 4,
    borderTopColor: COLORS.primaryGreen,
  },
  liveMatchesHeader: {
    marginBottom: 15,
  },
  liveMatchesTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  liveMatchesSubtitle: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontStyle: "italic",
  },
  toggleMatchesButton: {
    backgroundColor: COLORS.primaryGreen,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    marginBottom: 15,
    shadowColor: COLORS.accentGreen,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  toggleMatchesText: {
    fontSize: 14,
    fontWeight: "600",
    color: "white",
    marginBottom: 2,
  },
  matchesCount: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: "500",
  },
  matchesScrollView: {
    marginBottom: 15,
  },
  plantMatchCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginRight: 12,
    minWidth: 200,
    maxWidth: 220,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  goodMatchCard: {
    borderLeftWidth: 4,
    borderLeftColor: COLORS.success,
  },
  warningMatchCard: {
    borderLeftWidth: 4,
    borderLeftColor: COLORS.warning,
  },
  matchScoreBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: COLORS.success,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 40,
    alignItems: "center",
  },
  matchScoreText: {
    fontSize: 11,
    fontWeight: "700",
    color: "white",
  },
  plantMatchName: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 4,
    marginRight: 50, // Space for score badge
  },
  plantMatchCategory: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginBottom: 8,
    fontStyle: "italic",
  },
  matchReasonsContainer: {
    marginBottom: 10,
  },
  matchReason: {
    fontSize: 10,
    color: COLORS.textSecondary,
    marginBottom: 2,
    lineHeight: 14,
  },
  matchStatusBadge: {
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderRadius: 8,
    padding: 6,
    alignItems: "center",
  },
  matchStatusText: {
    fontSize: 10,
    fontWeight: "600",
    color: COLORS.success,
  },
  liveMatchesStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  statItem: {
    alignItems: "center",
  },
  statNumber: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.success,
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 10,
    color: COLORS.textSecondary,
    fontWeight: "500",
  },

  // Additional styles for analysis-style design
  liveCategoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
  },
  liveCategoryChipText: {
    fontSize: 12,
    fontWeight: '500',
  },
  liveStatusFilter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  liveStatusFilterText: {
    fontSize: 12,
    fontWeight: '500',
  },
  liveRecommendationCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  livePlantName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  livePlantCategory: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },

})
