import { StyleSheet } from "react-native"


export const COLORS = {
  primaryGreen: "#1D492C",
  accentGreen: "#84cc16",
  pastelGreen: "#BDE08A",
  lightGreen: "#f0fdf4",
  darkGreen: "#143820",
  mutedGreen: "#4C6444",
  grayText: "#666",
  border: "#e0e0e0",
  white: "#ffffff",
  bgCOlor: "#cfc4b2ff",
  primaryBrown: "#8A6440",
  secondaryBrown: "#ecc096ff",
  darkBrown: "#4D2D18",
  accent: "#FF6F00",
  accentLight: "#FFA726",
  background: "#CBBA9E",
  cardBackground: "#FFFFFF",
  textPrimary: "#1A1A1A",
  textSecondary: "#6B7280",
  textLight: "#9CA3AF",

  // Status colors
  success: "#4CAF50",
  warning: "#FFC107",
  error: "#8a1c14ff",
  info: "#2196F3",
}
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#CBBA9E",
  },

  headerBackground: {
    paddingTop: 50,
    paddingBottom: 40,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  greeting: {
    fontSize: 20,
    fontWeight: "700",
    color: "white",
    letterSpacing: 0.3,
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },

  plantCard: {
    backgroundColor: "#1c4722",
    borderRadius: 5,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 30,
    marginBottom: 24,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    overflow: "hidden",
  },
  plantCardContent: {
    padding: 24,
  },
  plantTextWrapper: {
    flex: 1,
  },
  plantName: {
    fontSize: 24,
    fontWeight: "800",
    color: COLORS.lightGreen,
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  plantTitle: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    marginTop: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  plantDetails: {
    color: "white",
    fontSize: 14,
    marginTop: 4,
    fontWeight: "500",
  },
  findPlantsButton: {
    marginTop: 20,
    backgroundColor: COLORS.lightGreen,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  findPlantsText: {
    color: "#1c4722",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.5,
  },

  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  sectionTitle: {
    marginBottom: 16,
    fontSize: 20,
    fontWeight: "900",
    color: COLORS.darkBrown,
    marginLeft: 4,
    letterSpacing: 0.3,
  },

  // Condition Card Styles - Redesigned
  conditionCard: {
    backgroundColor: "#8a644056",
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  conditionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
  },
  conditionHeaderLeft: {
    flex: 1,
  },
  conditionStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F8F0",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    alignSelf: "flex-start",
  },
  conditionStatusText: {
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  conditionSubtitle: {
    fontSize: 12,
    color: COLORS.primaryBrown,
    marginTop: 8,
    fontWeight: "500",
  },

  // Metrics Grid
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  metricCard: {
    width: "48%",
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  metricHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  metricLabel: {
    fontSize: 11,
    color: COLORS.primaryBrown,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  metricValue: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  metricRange: {
    fontSize: 11,
    color: COLORS.darkBrown,
    fontStyle: "italic",
  },
  metricStatus: {
    fontSize: 10,
    fontWeight: "600",
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Soil Moisture Card - Completely Redesigned
  soilMoistureCard: {
    backgroundColor: "#8a644056",
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  soilMoistureHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    paddingBottom: 16,
  },
  soilMoistureTitle: {
    color: COLORS.primaryBrown,
    fontWeight: "800",
    fontSize: 14,
    letterSpacing: 0.3,
  },
  soilViewButton: {
    backgroundColor: "#4d7f39",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    elevation: 2,
  },
  soilViewText: {
    color: "white",
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  moistureMainDisplay: {
    backgroundColor: "#F8FFF4",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureValueContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 8,
  },
  moistureLargeValue: {
    fontSize: 64,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: -2,
  },
  moistureUnit: {
    fontSize: 32,
    fontWeight: "700",
    color: "#4d7f39",
    marginLeft: 4,
  },
  moistureLabel: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  moistureRangeContainer: {
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureRangeLabel: {
    fontSize: 11,
    color: "#999",
    textAlign: "center",
    marginBottom: 4,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  moistureRangeValue: {
    fontSize: 16,
    color: "#2D5016",
    fontWeight: "700",
    textAlign: "center",
  },
  moistureStatusRow: {
    marginBottom: 16,
  },
  moistureStatusCard: {
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureStatusHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  moistureStatusText: {
    fontSize: 18,
    fontWeight: "800",
    marginLeft: 12,
    letterSpacing: 0.3,
  },
  moistureMessage: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
    marginLeft: 36,
  },
  moistureBarContainer: {
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  moistureBarLabel: {
    fontSize: 12,
    color: "#666",
    fontWeight: "600",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  moistureBarTrack: {
    height: 12,
    backgroundColor: "#E8E8E8",
    borderRadius: 6,
    overflow: "hidden",
    marginBottom: 8,
  },
  moistureBarFill: {
    height: "100%",
    borderRadius: 6,
  },
  moistureBarMarkers: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  moistureBarMarker: {
    fontSize: 10,
    color: "#999",
    fontWeight: "600",
  },
  plantHealthIndicator: {
    flexDirection: "row",
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  plantHealthIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    elevation: 2,
  },
  plantHealthText: {
    flex: 1,
  },
  plantHealthTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2D5016",
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  plantHealthDescription: {
    fontSize: 12,
    color: "#666",
    lineHeight: 18,
    fontWeight: "500",
  },

  // History Card - Redesigned
  historyCard: {
    backgroundColor: "#8a644056",
    borderRadius: 24,
    padding: 20,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  historyHeader: {
    marginBottom: 16,
  },
  historyHeaderRow: {
    flexDirection: "column",
    gap: 12,
  },
  historyTitle: {
    color: COLORS.primaryBrown,
    fontWeight: "800",
    fontSize: 18,
    letterSpacing: 0.3,
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.lightGreen,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  legendColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  legendText: {
    color: "#666",
    fontSize: 11,
    fontWeight: "600",
  },
  historyScrollView: {
    marginTop: 8,
  },
  historyScrollContent: {
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  scrollableHistoryDayWrapper: {
    marginRight: 12,
    alignItems: "center",
  },
  cleanDayBox: {
    width: 80,
    height: 100,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  cleanDayText: {
    color: "white",
    fontWeight: "700",
    fontSize: 11,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  cleanDateText: {
    color: "white",
    fontWeight: "800",
    fontSize: 32,
    marginBottom: 4,
    letterSpacing: -1,
  },
  cleanStatusText: {
    color: "white",
    fontWeight: "700",
    fontSize: 10,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Footer
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#1c4722",
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },

  // Modal Styles
  plantModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    padding: 20,
  },
  plantModalContainer: {
    backgroundColor: COLORS.lightGreen,
    borderRadius: 24,
    padding: 24,
    maxHeight: "85%",
    elevation: 12,
  },
  plantModalTitle: {
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 16,
    color: COLORS.primaryGreen,
    letterSpacing: 0.3,
  },
  selectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 10,
    color: COLORS.primaryGreen,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  chipScrollContainer: {
    maxHeight: 48,
    marginBottom: 12,
  },
  selectionChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#F0F8F0",
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  selectionChipActive: {
    backgroundColor: "#4d7f39",
    borderColor: "#4d7f39",
  },
  selectionChipText: {
    fontSize: 13,
    color: "#2D5016",
    fontWeight: "600",
  },
  selectionChipTextActive: {
    color: "#fff",
    fontWeight: "700",
  },
  categoryChipContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  plantList: {
    borderTopWidth: 1,
    borderColor: "#E8E8E8",
    marginTop: 8,
    maxHeight: 200,
  },
  plantItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderColor: "#F5F5F5",
    backgroundColor: "white",
  },
  plantItemContent: {
    flex: 1,
    marginRight: 12,
  },
  plantItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  plantItemName: {
    fontSize: 16,
    color: "#2D5016",
    fontWeight: "700",
    flex: 1,
    letterSpacing: 0.3,
  },
  recommendedBadge: {
    backgroundColor: "#4d7f39",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  recommendedText: {
    fontSize: 10,
    color: "#fff",
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  plantItemLocation: {
    fontSize: 13,
    color: "#666",
    fontStyle: "italic",
  },
  noLocationsText: {
    textAlign: "center",
    color: "#999",
    fontStyle: "italic",
    paddingVertical: 32,
    fontSize: 14,
  },
  closeModalBtn: {
    marginTop: 16,
    backgroundColor: COLORS.mutedGreen,
    paddingVertical: 14,
    borderRadius: 20,
    alignItems: "center",
    elevation: 2,
  },
  closeModalText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.5,
  },

  // History Modal Styles
  historyModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  historyModalContainer: {
    width: "95%",
    maxHeight: "90%",
    backgroundColor: "white",
    borderRadius: 24,
    padding: 24,
    elevation: 12,
  },
  historyModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#E8F5E8",
  },
  historyModalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: 0.3,
  },
  historyModalDate: {
    fontSize: 14,
    color: "#666",
    marginTop: 6,
    fontWeight: "500",
  },
  historyCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
  },
  historySummaryCard: {
    backgroundColor: "#F8FFF4",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  historyPlantInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  historyPlantName: {
    fontSize: 20,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: 0.3,
  },
  historyStatusBadge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    elevation: 2,
  },
  historyStatusText: {
    color: "white",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  historyStatsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E8F5E8",
  },
  historyStat: {
    alignItems: "center",
  },
  historyStatLabel: {
    fontSize: 11,
    color: "#666",
    marginBottom: 6,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  historyStatValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: -0.5,
  },
  historyAveragesCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  historySectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#2D5016",
    marginBottom: 16,
    letterSpacing: 0.3,
  },
  historyMetricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  historyMetricItem: {
    width: "48%",
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  historyMetricLabel: {
    fontSize: 11,
    color: "#666",
    marginBottom: 6,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  historyMetricValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#2D5016",
    letterSpacing: -0.5,
  },
  historyTimelineCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  timelineScroll: {
    marginTop: 12,
  },
  timelineItem: {
    width: 140,
    backgroundColor: "#F8FFF4",
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8F5E8",
  },
  timelineTimestamp: {
    fontSize: 13,
    fontWeight: "700",
    color: "#2D5016",
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  timelineReadings: {
    alignItems: "flex-start",
    width: "100%",
  },
  timelineReadingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  timelineReading: {
    fontSize: 12,
    color: "#666",
    marginLeft: 6,
    fontWeight: "500",
  },
  historyGraphCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  simpleGraph: {
    flexDirection: "row",
    alignItems: "flex-end",
    height: 140,
    marginTop: 16,
    paddingHorizontal: 8,
  },
  graphColumn: {
    flex: 1,
    alignItems: "center",
    height: "100%",
    justifyContent: "flex-end",
  },
  graphBar: {
    width: 16,
    marginBottom: 10,
    borderRadius: 8,
    minHeight: 12,
    elevation: 2,
  },
  graphLabel: {
    fontSize: 11,
    color: "#666",
    fontWeight: "600",
  },
})
