import { StyleSheet } from "react-native";

const COLORS = {
  primaryGreen: "#1D492C",
  accentGreen: "#84cc16",
  pastelGreen: "#BDE08A",
  lightGreen: "#f0fdf4",
  darkGreen: "#143820",
  mutedGreen: "#4C6444",
  error: "#8a1c14ff",
  grayText: "#666",
  border: "#e0e0e0",
  white: "#ffffff",
  bgCOlor: "#cfc4b2ff",
  primaryBrown: "#8A6440",
  darkBrown: "#4D2D18",
};

export default StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(32, 29, 29, 0.16)",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  scrollContent: {
    flexGrow: 1,
    paddingVertical: 40,
    alignItems: "center",
  },
  logo: {
    width: 85,
    height: 85,
    resizeMode: "contain",
    marginBottom: 15,
    justifyContent: "center",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6},
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 12,
  },
  card: {
    backgroundColor: "rgba(255, 255, 255, 0.61)",
    borderRadius: 25,
    padding: 30,
    width: "100%",
    maxWidth: 450,
  },
  title: {
    fontSize: 20,
    fontWeight: "900",
    color: COLORS.darkBrown,
    marginBottom: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 15,
    color: COLORS.primaryBrown,
    marginBottom: 30,
    textAlign: "center",
  },
  inputGroup: {
    marginBottom: 5,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.primaryGreen,
    marginBottom: 8,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f8f859",
    borderRadius: 25,
    borderWidth: 0.5,
    borderColor: COLORS.primaryGreen,
    paddingHorizontal: 15,
    height: 45,
  },
  inputContainerError: {
    borderColor: COLORS.error,
    borderWidth: 2,
    backgroundColor: "#FFF5F5",
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: "#333",
  },
  eyeIcon: {
    padding: 5,
  },
  helperText: {
    fontSize: 12,
    color: COLORS.lightGreen,
    marginTop: 6,
    marginLeft: 4,
  },
  errorText: {
    fontSize: 12,
    color: COLORS.error,
    marginTop: 6,
    marginLeft: 4,
    fontWeight: "500",
  },
  strengthContainer: {
    marginTop: 8,
    marginLeft: 4,
  },
  strengthBarContainer: {
    height: 4,
    backgroundColor: "#e0e0e0",
    borderRadius: 2,
    overflow: "hidden",
    marginBottom: 6,
  },
  strengthBar: {
    height: "100%",
    borderRadius: 2,
  },
  strengthText: {
    fontSize: 12,
    fontWeight: "600",
  },
  signUpButton: {
    backgroundColor: COLORS.mutedGreen,
    borderRadius: 25,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
    shadowColor: COLORS.grayText,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  signUpButtonDisabled: {
    backgroundColor: "#A5D6A7",
    opacity: 0.6,
  },
  signUpButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 25,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: "#999",
  },
  dividerText: {
    marginHorizontal: 15,
    fontSize: 13,
    color: "#999",
    fontWeight: "500",
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.pastelGreen,
    borderRadius: 25,
    borderWidth: 0,
    borderColor: "none",
    height: 45,
    paddingHorizontal: 20,
  },
  googleIcon: {
    width: 24,
    height: 24,
    marginRight: 12,
  },
  googleButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.primaryGreen,
  },
  footerContainer: {
    marginTop: 25,
    alignItems: "center",
  },
  footerText: {
    fontSize: 14,
    color: COLORS.primaryBrown,
    textAlign: "center",
  },
  footerLink: {
    color: COLORS.accentGreen,
    fontWeight: "600",
  },
});
